### ISSUE TITLE
Remove core modules from from `package.json`s dependencies

### ISSUE THREAD

**Issue by wooorm** [TuriGuilano/meesterproef#15]
`http` and `fs` are bundles with node, they’re not loaded from `node_modules/`, and shouldn’t be specified in [`package.json`](https://github.com/TuriGuilano/meesterproef/blob/32ab17bf20d7506146ef11b8b59df2873afe4a68/package.json#L31-L32).

**Comment by TuriGuilano** [comment]
I dont understand.. So I can require them without installing them because them come with node?

**Comment by wooorm** [comment]
Yup, that's essentially it!
