### ISSUE TITLE
dotenv: is `path: '.env'` needed?

### ISSUE THREAD

**Issue by wooorm** [TuriGuilano/meesterproef#16]
[`start.js#L4`](https://github.com/TuriGuilano/meesterproef/blob/32ab17bf20d7506146ef11b8b59df2873afe4a68/start.js#L4).

**Comment by wooorm** [comment]
Same in [`app.js`](https://github.com/TuriGuilano/meesterproef/blob/32ab17bf20d7506146ef11b8b59df2873afe4a68/app.js#L24).

**Comment by TuriGuilano** [comment]
No but its more neat right or? :x saw it in a node tutorial, thought it was nice to use as convention or so..

**Comment by TuriGuilano** [comment]
Your look on this?

**Comment by wooorm** [comment]
Well it's [the default](https://github.com/motdotla/dotenv/blob/master/README.md#path), so I'd say it's superfluous?!
